### ISSUE TITLE
Update to 1.6.1 to enable `registerFont`

### ISSUE THREAD

**Issue by epd** [chearon/node-canvas-prebuilt#1]
Hi there!

Thank you for creating such a wonderful module - it's opened up a lot of doors in infrastructure land being prebuilt.

`node-canvas` recently updated to 1.6.1 with a new method `Canvas.registerFont` which allows you to register 3rd-party font families to use within your Canvases.

Would it be possible to version bump? Happy to put in any work to contribute, just new to building bindings for different architectures.

Let me know how I can help!

**Comment by chearon** [comment]
> node-canvas recently updated to 1.6.1 with a new method Canvas.registerFont

I know, I made that! Actually, while they did merge in `Canvas.registerFont`and a bunch of other stuff to master, it hasn't been released yet, they'll be in version 2.0. [1.6.1](https://github.com/Automattic/node-canvas/commits/v1.6.1) was just a small fix to the `has_lib.sh` which wouldn't be affected by users here.

I'll be sure to build 2.0 when it gets released

**Comment by epd** [comment]
Doh! (on both parts).

Thanks for the quick response and for entertaining my impatience :) I'll close this out now!
