### ISSUE TITLE
libpng12.so.0 is missing on Debian Linux 9

### ISSUE THREAD

**Issue by kayahr** [chearon/node-canvas-prebuilt#15]
When I switch from `canvas`to `canvas-prebuilt` then my program crashes on Debian Linux 9 with the following error message:

```
Error: libpng12.so.0: cannot open shared object file: No such file or directory
```

I guess the problem ist, that you are creating the linux bundle on a Debian 8 system (or some linux which has the same problem). In Debian 8 for whatever reason libpng is installed in `/lib/` instead of `/usr/lib`. I don't think that this library can be considered to be a "system" library and it definitely should be included in your bundle. Maybe you could add an exception so everything in `/lib` is excluded except libpng? I manually copied the library from a Debian 8 system to the canvas directory and everything worked fine.

On Debian 9 there is no `libpng12.so.0` any longer, instead there is a `libpng16.so.16` now which is correctly located in `/usr/lib`. So maybe another solution would be switching your CI system to Debian 9.

**Comment by chearon** [comment]
Yeah I think upgrading to the OS that's doing it "right" would be better. That library should not be in `/lib`...

Which version did you get that error for? I have 2 different builds and the latest one (which is for 1.6.5-prerelease.1 and the 2 alpha versions I just published) uses Ubuntu Vivid. I'm not sure which Debian that's based on. I could probably check out the latest Ubuntu and see if it has the PNG library in the right place.

**Comment by kayahr** [comment]
I'm using 1.6.5-prerelease.1.

And Vivid is based on Debian 8 so this explains why libpng is in /lib. The current LTS release of Ubuntu (Xenial) is based on Debian 9 so if you insist on using Ubuntu then this might work, too. But as a Debian user I have to recommend Debian of course :)

**Comment by chearon** [comment]
I probably could use Debian, all I need is `apt-get` and a compiler. I'll see if I can get around to this today.

**Comment by chearon** [comment]
Hi @kayahr, I finally finished the new v4 Linux build (ended up using Debian, too) which bundles PNG. I've only updated the binaries for the `2.0.0-alpha.1` and `2.0.0-alpha.2` versions, though. I'll think about updating the other 4 versions on the `latest` tag later on. Last time I did, it was a disaster.
