### ISSUE TITLE
libgobject error on Ubuntu

### ISSUE THREAD

**Issue by mockdeep** [chearon/node-canvas-prebuilt#16]
I'm running into an issue loading `canvas-prebuilt` on our CI servers, which are running Ubuntu. They work fine for me on my local machine, so having some difficulty figuring out what to try next. When I `require('canvas-prebuilt')` I see the following error:

```
Error: /home/u4646/src/repo/synchroform/node_modules/canvas-prebuilt/canvas/build/Release/libgobject-2.0.so.0: undefined symbol: g_variant_dict_ref
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/u4646/src/repo/synchroform/node_modules/canvas-prebuilt/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Any idea what I'm missing here? I saw [this issue](https://github.com/chearon/node-canvas-prebuilt/issues/8) and wasn't sure if they were related. Happy to provide more information if I can get some tips on what else might be helpful.

**Comment by mockdeep** [comment]
```sh
$ uname -a
Linux worker-21482043.worker.solanoadmin.net 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by chearon** [comment]
It's almost for sure the same issue - the object code I'm shipping is linked against a newer glib than you have. That particular function was defined in 2.40... do you know if you can find out which one you have? One way is by looking up which distro, e.g. 17.04, and then checking the apt repos.

I'll try and find out more about the minimum GLib you need is. I would bundle it but last I tried that just caused more problems.

**Comment by mockdeep** [comment]
Looks like Solano is running 12.04 [according to their docs](http://docs.solanolabs.com/Setup/compatibility/), and as near as I can tell, [the glib version is 2.32.4](https://launchpad.net/ubuntu/precise/+source/glib2.0). Am I looking at this right? I'll also ping Solano and see if they have any suggestions.

**Comment by chearon** [comment]
Yup, you are. That's probably why. I'll need to figure out how to bundle GLib I think, in the meantime you would either need to figure out how to upgrade (don't know anything about Solano) or use Docker or something like that.

**Comment by soimy** [comment]
Please link with older glib version, or use `patchelf` to make it local by replacing path to `$ORIGIN`.
I'm unable to utilize travis-ci without this fix.

**Comment by chearon** [comment]
I've gotten close to a build that bundles glib and links against an old glibc. It's a bit time consuming because newer packages aren't available on older systems, so I have to compile a lot of packages individually.

I'll update this issue when I release it.

**Comment by chearon** [comment]
I've finished the new Linux build finally, which bundles `glib`. Unfortunately it won't work on 12.04, nor will I support it, since it is end-of-life since April. You need `glibc` >= 2.13.1, which is still several years old and will work on 14.04 or Debian Wheezy.

I have only updated the `2.0.0-alpha.1` and `2.0.0-alpha.2` binaries for the time being, which are on the `next` tag and must be installed explicitly. If all goes well I'll update the 1.6.x builds.
