### ISSUE TITLE
installation as fabric dependency

### ISSUE THREAD

**Issue by asturur** [chearon/node-canvas-prebuilt#4]
Hello, I'm Andrea, mantainer of fabric.js

Fabric rely on node-canvas for node operations and has normal canvas package as a dep.

Everyone complains that is a nightmare to install ( it is a nightmare on macosx and windows indeed )

I wanted to switch to this package to see if it would be better/faster for users to use fabric as a normal npm package.

I switched the dep and reinstalled.
Canvas installation is indeed instant and 0 logging.

I expected the replacement to work out of the box, but now the code cannot find the module canvas, that is named canvas-prebuilt.

Not a big deal since i recall it in a couple of lines, but before making the change i wanted to know if there is a way to have the module with the same name, or this thing would completely go against the npm logic?

**Comment by asturur** [comment]
Something is not clear to me.
I require canvas-prebuilt, but it does not work as expected. I get errors.
I replace all instances of require('canvas') with require('canvas-prebuilt') but i get errors.

**Comment by chearon** [comment]
Hi there! It is indeed a nightmare to compile, it seems like 75% of the issues posted in node-canvas are in one way or another about compiling.

I looked for a way to allow it to work with `require('canvas')` but it looked to be impossible, [here](https://nodejs.org/api/modules.html#modules_all_together) is the algorithm Node uses to resolve a string into the module.

What errors were you getting when you replaced `canvas` with `canvas-prebuilt`? As long as you do the `npm install canvas-prebuilt` that should work... I can try playing around with fabric.js sometime soon to see if I can reproduce your issues.

The best way I can think of to get `require('canvas')` working would be to have the node-canvas use `node-pre-gyp` and download the binaries from here.... I should probably just make that PR. In the meantime I think you'd have to change `canvas` to `canvas-prebuilt`. Also, consider that I only have the most popular processor architectures done at the moment

**Comment by asturur** [comment]
i mostly care about x64.
both my macosx sierra and travis from github are failing.

look the code changes i did are pretty self explanatory, clicking on the red cross you see error in travis. something is different in the context or the canvas object.

https://github.com/kangax/fabric.js/pull/3757

**Comment by chearon** [comment]
I can't get your tests to run on `master` either, are you sure it didn't break somewhere else? Seems like the fabric variable isn't defined in some places where it should be

**Comment by chearon** [comment]
I'm not sure if JSDom can work with `canvas-prebuilt` right now because [it does a `require('canvas')`](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/utils.js#L215). I tried changing that line to -prebuilt and the tests seemed to be similar to master. I can't reproduce the error that the CI is getting though.

Either I have to convince @LinusU to use prebuilt binaries for `canvas` or you would have to figure out how to remove jsdom as a dependency (if that's even possible?). Or convince jsdom to try for `require('canvas-prebuilt')`.

**Comment by asturur** [comment]
oh so jsdom is managing it....
that would be good and bad.

also jsdom could have an option to use prebuilt or a post script install to
rename the canvasprebuilt folder to canvas.

i ll see what they do and if they are open to changes since jsdom does not
require canvas itself.

test do not run in master now if you do not run npm run build before, since
the built lib in dist folder expect jsdom 3 and i just switched to 9.

**Comment by asturur** [comment]
i opened this https://github.com/tmpvar/jsdom/pull/1754

**Comment by asturur** [comment]
the jsdom PR has been merged.
i guess jsdom will get a dep bump and i can close my issue.
