### ISSUE TITLE
pango support

### ISSUE THREAD

**Issue by asturur** [chearon/node-canvas-prebuilt#5]
Hello Chearon,

Would you be so kind to explain in some way what is the difference of node canvas when is built with pango support or not, if pango is complementar to cairo or is on top of it, or in place of it and how this affect text rendering?

I have lot of confusion around this when people open node related question on fabricjs issue tracker.

Is a prebuilt version with pango available?

**Comment by chearon** [comment]
Hey, see [here](https://github.com/Automattic/node-canvas/pull/715) for the differences between those builds. Basically if you have Pango you get a very different implementation of custom fonts than if you don't, but more languages/glyphs should work correctly with it. Pango complements Cairo and renders to it as a "backend".

When canvas 2.0 gets released, there won't be 2 different builds, just the Pango one. Prebuilt 1.4-1.6 should be using the Pango build, though... I'll double check that. What issues are people having in fabricjs?

**Comment by asturur** [comment]
Mainly text, sometimes shadows.
i rewrote fabricjs text support to be more stable and similar across the two platform and now i have to go with testing. so if use prebuilt version i m still on the best available solution?

**Comment by chearon** [comment]
Currently I think there's an issue with the Pango I'm shipping for Linux, I'm gonna try to have that fixed very soon. Other than that I don't think there are going to be any differences with canvas

**Comment by chearon** [comment]
I finally got the fix for Pango on Linux working, it involved redoing a lot of the build due to Travis's outdated Ubuntu distribution. Pushing up the new versions now
